### ISSUE TITLE
SubActivity重复requestLayout()警告

### ISSUE THREAD

**Issue by kHRYSTAL** [yanbober/Android-Blog-Source#1]
你好 我在用您的SubActivity做测试用例 出现了
15741-15741/com.yanbober.support_v2220_demo W/View﹕ requestLayout() improperly called by android.support.v7.widget.Toolbar{23ad06c5 V.E..... ......ID 0,0-1080,168 #7f0c006a app:id/tool_bar} during layout: running second layout pass
 15741-15741/com.yanbober.support_v2220_demo W/View﹕ requestLayout() improperly called by android.support.design.widget.CollapsingToolbarLayout{25e8ff2f V.ED.... ......I. 0,0-1080,600 #7f0c006f app:id/collapsing_toolbar} during second layout pass: posting in next frame
 我把中间的Linear布局替换成了WebView 结果WebView与Toolbar之间出现间距 拖动后自动重绘视图
请问如何解决

**Comment by yanbober** [comment]
@kHRYSTAL 请检查你的包导入问题
